default_install_hook_types: [pre-commit, commit-msg]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: \.(md|md\.j2)$
    stages: [pre-commit]
  - id: mixed-line-ending
    stages: [pre-commit]
  - id: check-yaml
    stages: [pre-commit]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      stages: [pre-commit]
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.2.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.264'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
      stages: [pre-commit]
